stages:
  - debug
  - test
variables:
  USER_AGENT: "KFC-Playwright-CI/1.0 (+GitLab CI)"
  PIPELINE_GUID: "6f8a3d47-2b1f-4b1e-8f8f-1c2b3a4d5e6f"
debug-network:
  stage: debug
  image: curlimages/curl:7.87.0
  script:
    #- echo "Checking connectivity to QA site without headers..."
    #- 'curl -vI "https://qa.kfc-digital.io/" || echo "Failed without headers"'
    - echo "Checking connectivity with headers..."
    - 'curl -vI -H "User-Agent: $USER_AGENT" -H "X-KFC-PIPELINE: $PIPELINE_GUID" "https://qa.kfc-digital.io/" || echo "Failed with headers"'
    - echo "Testing HTTP/1.1 (bypassing HTTP/2)..."
    - 'curl -vI --http1.1 -H "User-Agent: $USER_AGENT" -H "X-KFC-PIPELINE: $PIPELINE_GUID" "https://qa.kfc-digital.io/" || echo "HTTP/1.1 test failed"'
playwright-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.47.1-jammy
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
      - .cache/ms-playwright/
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report
      - test-results
    reports:
      junit: test-results/results.xml
    expire_in: 1 week
